using System.Globalization;

namespace DueMap.Web.Services;

/// <summary>
/// Cache-busting stamps for compiled static assets.
///
/// app.css is regenerated by Tailwind on every build, but the URL never changes,
/// so browsers happily keep serving the previous copy. That produces the worst
/// kind of dev-loop bug: the source is correct, the build succeeded, the served
/// file is correct, and the page still renders with the old styling.
///
/// Stamping the URL with the file's last-write time makes the URL change exactly
/// when the bytes do — fresh after a rebuild, cacheable in between.
/// </summary>
public static class AssetVersion
{
    /// <summary>Version stamp for wwwroot/css/app.css.</summary>
    public static string Css { get; } = StampFor("wwwroot/css/app.css");

    private static string StampFor(string relativePath)
    {
        try
        {
            var full = Path.Combine(AppContext.BaseDirectory, relativePath);
            if (!File.Exists(full))
            {
                // In dev the content root is the project dir, not the bin output.
                full = Path.Combine(Directory.GetCurrentDirectory(), relativePath);
            }

            return File.Exists(full)
                ? File.GetLastWriteTimeUtc(full).Ticks.ToString(CultureInfo.InvariantCulture)
                : FallbackStamp;
        }
        catch (IOException)
        {
            return FallbackStamp;
        }
        catch (UnauthorizedAccessException)
        {
            return FallbackStamp;
        }
    }

    // Process start time: still busts the cache across restarts, which is the
    // case that matters, without pretending we know the asset's real version.
    private static readonly string FallbackStamp =
        System.Diagnostics.Process.GetCurrentProcess().StartTime.ToUniversalTime().Ticks.ToString(CultureInfo.InvariantCulture);
}
